name: scottmills
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b9233a'
    - '#f9c733'
    - '#f0623a'
    - '#6a617b'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
